# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1007, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pantheon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.atheneaStages = QtWidgets.QStackedWidget(self.centralwidget)
        self.atheneaStages.setObjectName("atheneaStages")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.MainPage)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.buildTab = QtWidgets.QWidget()
        self.buildTab.setObjectName("buildTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.buildTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buildInfoLayout = QtWidgets.QHBoxLayout()
        self.buildInfoLayout.setObjectName("buildInfoLayout")
        self.buildFiltersLayout = QtWidgets.QVBoxLayout()
        self.buildFiltersLayout.setObjectName("buildFiltersLayout")
        self.filterByText = QtWidgets.QHBoxLayout()
        self.filterByText.setObjectName("filterByText")
        self.filterTitle = QtWidgets.QLabel(self.buildTab)
        self.filterTitle.setEnabled(True)
        self.filterTitle.setObjectName("filterTitle")
        self.filterByText.addWidget(self.filterTitle)
        self.buildFilterSearch = QtWidgets.QLineEdit(self.buildTab)
        self.buildFilterSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildFilterSearch.sizePolicy().hasHeightForWidth())
        self.buildFilterSearch.setSizePolicy(sizePolicy)
        self.buildFilterSearch.setMinimumSize(QtCore.QSize(0, 10))
        self.buildFilterSearch.setObjectName("buildFilterSearch")
        self.filterByText.addWidget(self.buildFilterSearch)
        self.buildFiltersLayout.addLayout(self.filterByText)
        self.filtersScrollArea = QtWidgets.QScrollArea(self.buildTab)
        self.filtersScrollArea.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtersScrollArea.sizePolicy().hasHeightForWidth())
        self.filtersScrollArea.setSizePolicy(sizePolicy)
        self.filtersScrollArea.setWidgetResizable(True)
        self.filtersScrollArea.setObjectName("filtersScrollArea")
        self.filtersScrollAreaLayout = QtWidgets.QWidget()
        self.filtersScrollAreaLayout.setGeometry(QtCore.QRect(0, 0, 193, 378))
        self.filtersScrollAreaLayout.setObjectName("filtersScrollAreaLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filtersScrollAreaLayout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filtersTree = QtWidgets.QTreeWidget(self.filtersScrollAreaLayout)
        self.filtersTree.setEnabled(False)
        self.filtersTree.setUniformRowHeights(True)
        self.filtersTree.setAnimated(True)
        self.filtersTree.setColumnCount(1)
        self.filtersTree.setObjectName("filtersTree")
        self.verticalLayout_2.addWidget(self.filtersTree)
        self.filtersScrollArea.setWidget(self.filtersScrollAreaLayout)
        self.buildFiltersLayout.addWidget(self.filtersScrollArea)
        self.buildFiltersLayout.setStretch(1, 10)
        self.buildInfoLayout.addLayout(self.buildFiltersLayout)
        self.Separator_1 = QtWidgets.QFrame(self.buildTab)
        self.Separator_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.Separator_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separator_1.setObjectName("Separator_1")
        self.buildInfoLayout.addWidget(self.Separator_1)
        self.buildNodesTreeLayout = QtWidgets.QVBoxLayout()
        self.buildNodesTreeLayout.setObjectName("buildNodesTreeLayout")
        self.buildNodesStackedWidget = QtWidgets.QStackedWidget(self.buildTab)
        self.buildNodesStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buildNodesStackedWidget.setObjectName("buildNodesStackedWidget")
        self.buildTreeModelPage = QtWidgets.QWidget()
        self.buildTreeModelPage.setObjectName("buildTreeModelPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.buildTreeModelPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buildNodesTree = QtWidgets.QTreeWidget(self.buildTreeModelPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildNodesTree.sizePolicy().hasHeightForWidth())
        self.buildNodesTree.setSizePolicy(sizePolicy)
        self.buildNodesTree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.buildNodesTree.setUniformRowHeights(False)
        self.buildNodesTree.setAnimated(True)
        self.buildNodesTree.setHeaderHidden(False)
        self.buildNodesTree.setObjectName("buildNodesTree")
        self.buildNodesTree.header().setDefaultSectionSize(375)
        self.verticalLayout_5.addWidget(self.buildNodesTree)
        self.buildNodesStackedWidget.addWidget(self.buildTreeModelPage)
        self.buildFilteredListPage = QtWidgets.QWidget()
        self.buildFilteredListPage.setObjectName("buildFilteredListPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.buildFilteredListPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.buildFilteredItemList = QtWidgets.QListWidget(self.buildFilteredListPage)
        self.buildFilteredItemList.setProperty("showDropIndicator", False)
        self.buildFilteredItemList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.buildFilteredItemList.setObjectName("buildFilteredItemList")
        self.verticalLayout_6.addWidget(self.buildFilteredItemList)
        self.buildNodesStackedWidget.addWidget(self.buildFilteredListPage)
        self.buildNodesTreeLayout.addWidget(self.buildNodesStackedWidget)
        self.buildInfoLayout.addLayout(self.buildNodesTreeLayout)
        self.Separator_2 = QtWidgets.QFrame(self.buildTab)
        self.Separator_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.Separator_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separator_2.setObjectName("Separator_2")
        self.buildInfoLayout.addWidget(self.Separator_2)
        self.ItemsToBuild = QtWidgets.QVBoxLayout()
        self.ItemsToBuild.setObjectName("ItemsToBuild")
        self.itemsToBuildTitle = QtWidgets.QLabel(self.buildTab)
        self.itemsToBuildTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.itemsToBuildTitle.setObjectName("itemsToBuildTitle")
        self.ItemsToBuild.addWidget(self.itemsToBuildTitle)
        self.itemsList = QtWidgets.QListWidget(self.buildTab)
        self.itemsList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.itemsList.setProperty("showDropIndicator", False)
        self.itemsList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.itemsList.setAlternatingRowColors(True)
        self.itemsList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.itemsList.setIconSize(QtCore.QSize(16, 16))
        self.itemsList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.itemsList.setObjectName("itemsList")
        self.ItemsToBuild.addWidget(self.itemsList)
        self.buildInfoLayout.addLayout(self.ItemsToBuild)
        self.buildInfoLayout.setStretch(0, 3)
        self.buildInfoLayout.setStretch(2, 7)
        self.verticalLayout_4.addLayout(self.buildInfoLayout)
        self.buildFilteredItempath = QtWidgets.QLabel(self.buildTab)
        self.buildFilteredItempath.setEnabled(True)
        self.buildFilteredItempath.setText("")
        self.buildFilteredItempath.setObjectName("buildFilteredItempath")
        self.verticalLayout_4.addWidget(self.buildFilteredItempath)
        self.buildButtonsLayout = QtWidgets.QHBoxLayout()
        self.buildButtonsLayout.setObjectName("buildButtonsLayout")
        self.buttonBuildRefresh = QtWidgets.QPushButton(self.buildTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonBuildRefresh.sizePolicy().hasHeightForWidth())
        self.buttonBuildRefresh.setSizePolicy(sizePolicy)
        self.buttonBuildRefresh.setObjectName("buttonBuildRefresh")
        self.buildButtonsLayout.addWidget(self.buttonBuildRefresh)
        self.buttonBuildStep1 = QtWidgets.QPushButton(self.buildTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonBuildStep1.sizePolicy().hasHeightForWidth())
        self.buttonBuildStep1.setSizePolicy(sizePolicy)
        self.buttonBuildStep1.setObjectName("buttonBuildStep1")
        self.buildButtonsLayout.addWidget(self.buttonBuildStep1)
        self.buttonBuildStep2 = QtWidgets.QPushButton(self.buildTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonBuildStep2.sizePolicy().hasHeightForWidth())
        self.buttonBuildStep2.setSizePolicy(sizePolicy)
        self.buttonBuildStep2.setObjectName("buttonBuildStep2")
        self.buildButtonsLayout.addWidget(self.buttonBuildStep2)
        self.buildButtonsLayout.setStretch(0, 1)
        self.buildButtonsLayout.setStretch(1, 2)
        self.buildButtonsLayout.setStretch(2, 2)
        self.verticalLayout_4.addLayout(self.buildButtonsLayout)
        self.buildConsoleLayout = QtWidgets.QHBoxLayout()
        self.buildConsoleLayout.setObjectName("buildConsoleLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.buildTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 943, 161))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.consoleOutput = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.consoleOutput.setText("")
        self.consoleOutput.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.consoleOutput.setWordWrap(True)
        self.consoleOutput.setOpenExternalLinks(True)
        self.consoleOutput.setObjectName("consoleOutput")
        self.horizontalLayout.addWidget(self.consoleOutput)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buildConsoleLayout.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.buildConsoleLayout)
        self.buildProgressBar = QtWidgets.QProgressBar(self.buildTab)
        self.buildProgressBar.setEnabled(True)
        self.buildProgressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buildProgressBar.setProperty("value", 0)
        self.buildProgressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.buildProgressBar.setTextVisible(True)
        self.buildProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.buildProgressBar.setInvertedAppearance(False)
        self.buildProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.buildProgressBar.setObjectName("buildProgressBar")
        self.verticalLayout_4.addWidget(self.buildProgressBar)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(3, 2)
        self.tabWidget.addTab(self.buildTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settingsTab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingsLayout = QtWidgets.QVBoxLayout()
        self.settingsLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.settingsLayout.setObjectName("settingsLayout")
        self.pathsContainer = QtWidgets.QFrame(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathsContainer.sizePolicy().hasHeightForWidth())
        self.pathsContainer.setSizePolicy(sizePolicy)
        self.pathsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pathsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pathsContainer.setObjectName("pathsContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pathsContainer)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.settingsLayout.addWidget(self.pathsContainer)
        self.verticalLayout_7.addLayout(self.settingsLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.buttonApply = QtWidgets.QPushButton(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonApply.sizePolicy().hasHeightForWidth())
        self.buttonApply.setSizePolicy(sizePolicy)
        self.buttonApply.setObjectName("buttonApply")
        self.buttonsLayout.addWidget(self.buttonApply)
        self.buttonCancel = QtWidgets.QPushButton(self.settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCancel.sizePolicy().hasHeightForWidth())
        self.buttonCancel.setSizePolicy(sizePolicy)
        self.buttonCancel.setObjectName("buttonCancel")
        self.buttonsLayout.addWidget(self.buttonCancel)
        self.verticalLayout_7.addLayout(self.buttonsLayout)
        self.tabWidget.addTab(self.settingsTab, "")
        self.moreToComeTab = QtWidgets.QWidget()
        self.moreToComeTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.moreToComeTab.setObjectName("moreToComeTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.moreToComeTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.WIPLabel = QtWidgets.QLabel(self.moreToComeTab)
        self.WIPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WIPLabel.setObjectName("WIPLabel")
        self.verticalLayout_3.addWidget(self.WIPLabel)
        self.tabWidget.addTab(self.moreToComeTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.projectTitle = QtWidgets.QLabel(self.MainPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.projectTitle.setFont(font)
        self.projectTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.projectTitle.setObjectName("projectTitle")
        self.gridLayout_2.addWidget(self.projectTitle, 0, 0, 1, 1)
        self.tabWidget.raise_()
        self.tabWidget.raise_()
        self.projectTitle.raise_()
        self.atheneaStages.addWidget(self.MainPage)
        self.WelcomePage = QtWidgets.QWidget()
        self.WelcomePage.setObjectName("WelcomePage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.WelcomePage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Login = QtWidgets.QWidget(self.WelcomePage)
        self.Login.setObjectName("Login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Login)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.Login)
        font = QtGui.QFont()
        font.setPointSize(59)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.LogiBox = QtWidgets.QWidget(self.Login)
        self.LogiBox.setObjectName("LogiBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.LogiBox)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.userWidget = QtWidgets.QWidget(self.LogiBox)
        self.userWidget.setObjectName("userWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.userWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.userWidget)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.userLine = QtWidgets.QLineEdit(self.userWidget)
        self.userLine.setEnabled(False)
        self.userLine.setMaximumSize(QtCore.QSize(300, 16777215))
        self.userLine.setObjectName("userLine")
        self.horizontalLayout_3.addWidget(self.userLine)
        self.verticalLayout_8.addWidget(self.userWidget)
        self.Password = QtWidgets.QWidget(self.LogiBox)
        self.Password.setObjectName("Password")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Password)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.Password)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.passwordLine = QtWidgets.QLineEdit(self.Password)
        self.passwordLine.setEnabled(False)
        self.passwordLine.setMaximumSize(QtCore.QSize(300, 16777215))
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.horizontalLayout_5.addWidget(self.passwordLine)
        self.label_2.raise_()
        self.passwordLine.raise_()
        self.verticalLayout_8.addWidget(self.Password)
        self.projects = QtWidgets.QScrollArea(self.LogiBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projects.sizePolicy().hasHeightForWidth())
        self.projects.setSizePolicy(sizePolicy)
        self.projects.setWidgetResizable(True)
        self.projects.setObjectName("projects")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 933, 210))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.projectList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.projectList.setObjectName("projectList")
        self.verticalLayout_10.addWidget(self.projectList)
        self.Login.raise_()
        self.projectList.raise_()
        self.label_5.raise_()
        self.projects.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.projects)
        self.loginButton = QtWidgets.QPushButton(self.LogiBox)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_8.addWidget(self.loginButton)
        self.verticalLayout.addWidget(self.LogiBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 242, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.Login)
        self.atheneaStages.addWidget(self.WelcomePage)
        self.gridLayout.addWidget(self.atheneaStages, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Pantheon = QtWidgets.QAction(MainWindow)
        self.actionAbout_Pantheon.setObjectName("actionAbout_Pantheon")
        self.actionReport_an_Issue = QtWidgets.QAction(MainWindow)
        self.actionReport_an_Issue.setObjectName("actionReport_an_Issue")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Pantheon)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReport_an_Issue)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.atheneaStages.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.buildNodesStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Atenea"))
        self.filterTitle.setText(_translate("MainWindow", "Search:"))
        self.filtersTree.headerItem().setText(0, _translate("MainWindow", "Filters"))
        self.buildNodesTree.headerItem().setText(0, _translate("MainWindow", "Art"))
        self.buildNodesTree.headerItem().setText(1, _translate("MainWindow", "Status"))
        self.itemsToBuildTitle.setText(_translate("MainWindow", "Items To Build:"))
        self.buttonBuildRefresh.setText(_translate("MainWindow", "Refresh"))
        self.buttonBuildStep1.setText(_translate("MainWindow", "Build Step 1"))
        self.buttonBuildStep2.setText(_translate("MainWindow", "Build Step 2"))
        self.buildProgressBar.setFormat(_translate("MainWindow", "%p%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buildTab), _translate("MainWindow", "Export"))
        self.buttonApply.setText(_translate("MainWindow", "Apply"))
        self.buttonCancel.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.WIPLabel.setText(_translate("MainWindow", "NEW TOOLS COMMING!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.moreToComeTab), _translate("MainWindow", "More To Come"))
        self.projectTitle.setText(_translate("MainWindow", "Project Name"))
        self.label_4.setText(_translate("MainWindow", "ATHENEA"))
        self.label.setText(_translate("MainWindow", "User"))
        self.userLine.setText(_translate("MainWindow", "AtheneaUser"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.passwordLine.setText(_translate("MainWindow", "AtheneaUser+"))
        self.label_5.setText(_translate("MainWindow", "Projects"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout_Pantheon.setText(_translate("MainWindow", "About Pantheon"))
        self.actionReport_an_Issue.setText(_translate("MainWindow", "Report an Issue"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
